import Link from "next/link";
import { BRAND } from "@/lib/brand";
export const metadata = { title: `Terms · ${BRAND.name}` };
export default function Terms() {
  return <article>
    <h1>Terms of use</h1><p><small>Last updated 7 October 2026</small></p>
    <p>By creating an account or using {BRAND.name}, you agree to these terms. They are written to be readable, so please do read them.</p>
    <h2>What the service is</h2>
    <p>{BRAND.name} helps you plan and draft writing by asking about your situation first. It connects to an AI account that you provide. We do not supply the AI.</p>
    <h2>Your account</h2>
    <p>Keep your login details safe and give us accurate information. You are responsible for activity on your account.</p>
    <h2>Your content</h2>
    <p>What you write, upload and create remains yours. You give us permission only to store and process it so the service can work for you, including sending it to the AI provider you connected. Only upload or paste material you have the right to use.</p>
    <h2>AI can be wrong</h2>
    <p>Drafts are generated by AI and may contain mistakes, even though {BRAND.name} is designed not to invent personal details and flags claims it cannot trace to your context. Review everything, and check facts, names, figures and sources before you rely on or share a piece. You are responsible for how you use what you create.</p>
    <h2>Schools, work and honesty</h2>
    <p>Some schools, employers and publishers have rules about AI-assisted writing. It is your responsibility to follow the rules that apply to you and to be open about your use of AI where required.</p>
    <h2>Your AI account and costs</h2>
    <p>You pay your AI provider directly for the requests made with your key, and you are bound by their terms. Keep your key private. {BRAND.name} does not control or reimburse those charges.</p>
    <h2>Acceptable use</h2>
    <p>Do not use the service to break the law, harass or deceive others, upload material that infringes someone's rights or contains other people's private information without permission, attempt to bypass limits or security, or interfere with the service for other users.</p>
    <h2>Availability</h2>
    <p>We work to keep the service running, but it is provided as it is, without guarantees. Features may change, and the service may occasionally be unavailable. To the extent the law allows, we are not liable for indirect or consequential losses, or for losses caused by AI output or your provider's services.</p>
    <h2>Ending your use</h2>
    <p>You can delete your account at any time from the Account page. We may suspend accounts that break these terms.</p>
    <h2>Changes and contact</h2>
    <p>If these terms change in a way that matters, we will update the date above, and continuing to use the service means you accept the update.{BRAND.contactEmail ? <> Questions? Email <a href={`mailto:${BRAND.contactEmail}`}>{BRAND.contactEmail}</a>.</> : <> Questions? Use the feedback button inside the app.</>}</p>
    <p><Link href="/privacy">Read the Privacy page</Link></p>
  </article>;
}
